FROM python:3.9
USER root
COPY . /src/
RUN chown -r 1000:1000 /src
USER 1000
WORKDIR /src

ENV HOME=/src
RUN pip install --user pipenv
RUN python -m pipenv install
RUN mkdir -p /src/assets
ENV PYTHONPATH=/src
RUN python -m pipenv run python /src/bin/download_models.py

CMD ["python", "-m", "pipenv", "run", "/src/bin/start_server"]
