app:
  # Obligatoriska nycklar/värden
  description: "Makes sure that the KB/BERT models are running and accessable for other services in a micro-architecture environment"
  owner: "AI-hubben"
  documentation: "Länk till dokumentation"
  repository: "Länk till git repo"
  runbook: "Länk till driftsdokumentation"

  # Rekommenderade nycklar/värden
  chat: "AI-hub"
  incidents: "Skulle kunna vara en länk till t.ex. Jira eller EMS"
  uptime: "T.ex. en länk till en dashboard i Grafana"
  performance: "T.ex. en länk till en dashboard i Grafana"
  dependencies: "Länk till systemet för systemöversikt eller en kort beskrivning i textform"

image:
  repository: "bolagsverket/tek/aihub/bms"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

extraEnvs:
  - name: "PORT"
    value: "8081"



blvEnvMode: dev
blvEnvModeNr: dev01



imagePullSecrets: []
containerPort: 8080
nameOverride: ""
fullnameOverride: ""
restartPolicy: Always





serviceAccount:
  create: true

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000


ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: bert-models
      paths:
        - /(.*)
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 1Gi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# TODO: Kan inte använda en startupProbe, inget stöd i blv-app-template?!
#startupProbe:
#  httpGet:
#    path: /valavforetagsnamn/actuator/health/liveness
#    port: 8080
#  failureThreshold: 30
#  periodSeconds: 10

#livenessProbe:
#  httpGet:
#    path: /valavforetagsnamn/actuator/health/liveness
#    port: 8080
#  initialDelaySeconds: 40
#  periodSeconds: 10
#  timeoutSeconds: 5
#  successThreshold: 1
#  failureThreshold: 3

#readinessProbe:
#  httpGet:
#    path: /valavforetagsnamn/actuator/health/readiness
#    port: 8080
#  initialDelaySeconds: 50
#  periodSeconds: 10
#  timeoutSeconds: 1
#  successThreshold: 1
#  failureThreshold: 3
#
extraArgs: {}
# Pass extra command argumens to container

extraVolumeMounts: {}

extraVolumes: {}

configurationFiles: {}
#  application.properties: |-
#
#    example.property=true


# Suffix att lägga till ett hostnamn för att få ett internt kvalificerat FQDN.
# Testmiljö: -system.system.bolagsverket.se
# Prod: .prod.bolagsverket.se
fqdnSuffixInternal: ""

# Suffix att lägga till ett hostnamn för att få ett externt FQDN.
# Testmiljö: -system.bolagsverket.se
# Prod: .bolagsverket.se
fqdnSuffixExternal: ""
